#!/usr/bin/env ruby

require ENV['HOME'] + '/project/kbd-input/kbd-input.rb'

k = Keyboard.new()

macros = YAML.load(File.open(ENV['HOME'] + "/.keyboarding.yaml"))

macro = macros[ARGV[0]]
unless macro.nil?
  str = macro['string']
  unless str.nil?
    k.type_string(str)
  end
  code = macro['code']
  unless code.nil?
    # eval(code)
    puts "The code is:"
    puts code
    eval(code)
  end
end

k.close()

